// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindTodoParams creates a new FindTodoParams object
// with the default values initialized.
func NewFindTodoParams() *FindTodoParams {
	var ()
	return &FindTodoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindTodoParamsWithTimeout creates a new FindTodoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindTodoParamsWithTimeout(timeout time.Duration) *FindTodoParams {
	var ()
	return &FindTodoParams{

		timeout: timeout,
	}
}

// NewFindTodoParamsWithContext creates a new FindTodoParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindTodoParamsWithContext(ctx context.Context) *FindTodoParams {
	var ()
	return &FindTodoParams{

		Context: ctx,
	}
}

// NewFindTodoParamsWithHTTPClient creates a new FindTodoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindTodoParamsWithHTTPClient(client *http.Client) *FindTodoParams {
	var ()
	return &FindTodoParams{
		HTTPClient: client,
	}
}

/*FindTodoParams contains all the parameters to send to the API endpoint
for the find todo operation typically these are written to a http.Request
*/
type FindTodoParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find todo params
func (o *FindTodoParams) WithTimeout(timeout time.Duration) *FindTodoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find todo params
func (o *FindTodoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find todo params
func (o *FindTodoParams) WithContext(ctx context.Context) *FindTodoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find todo params
func (o *FindTodoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find todo params
func (o *FindTodoParams) WithHTTPClient(client *http.Client) *FindTodoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find todo params
func (o *FindTodoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find todo params
func (o *FindTodoParams) WithID(id int64) *FindTodoParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find todo params
func (o *FindTodoParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindTodoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
